//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BS.DB.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ShopsInPostalCodes
    {
        public int ID { get; set; }
        public int ShopID { get; set; }
        [Display(Name="Postal Code")]
        //[MaxLength(6),MinLength(6)]
        [DataType(dataType:DataType.PostalCode)]
        public int PostalCodeID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual TBL_PostalCodes_CNFG TBL_PostalCodes_CNFG { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails { get; set; }

        public virtual TBL_Shops TBL_Shops { get; set; }
    }
}
