//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.DB.EntityFW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BSDBEntities : DbContext
    {
        public BSDBEntities()
            : base("name=BSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_AdminOffers> TBL_AdminOffers { get; set; }
        public virtual DbSet<TBL_Cities_CNFG> TBL_Cities_CNFG { get; set; }
        public virtual DbSet<TBL_InActiveShopList_CNFG> TBL_InActiveShopList_CNFG { get; set; }
        public virtual DbSet<TBL_InActiveShopReasons_CNFG> TBL_InActiveShopReasons_CNFG { get; set; }
        public virtual DbSet<TBL_Infrastructure_CNFG> TBL_Infrastructure_CNFG { get; set; }
        public virtual DbSet<TBL_InfrastructureCategories_CNFG> TBL_InfrastructureCategories_CNFG { get; set; }
        public virtual DbSet<TBL_OfferOnProducts> TBL_OfferOnProducts { get; set; }
        public virtual DbSet<TBL_PostalCodes_CNFG> TBL_PostalCodes_CNFG { get; set; }
        public virtual DbSet<TBL_ProductCategories_CNFG> TBL_ProductCategories_CNFG { get; set; }
        public virtual DbSet<TBL_ProductImages> TBL_ProductImages { get; set; }
        public virtual DbSet<TBL_Products> TBL_Products { get; set; }
        public virtual DbSet<TBL_ProductSubType_CNFG> TBL_ProductSubType_CNFG { get; set; }
        public virtual DbSet<TBL_ProductType_CNFG> TBL_ProductType_CNFG { get; set; }
        public virtual DbSet<TBL_ShopCategory_CNFG> TBL_ShopCategory_CNFG { get; set; }
        public virtual DbSet<TBL_ShopDirectory> TBL_ShopDirectory { get; set; }
        public virtual DbSet<TBL_ShopLoginDetails> TBL_ShopLoginDetails { get; set; }
        public virtual DbSet<TBL_ShopOffers> TBL_ShopOffers { get; set; }
        public virtual DbSet<TBL_Shops> TBL_Shops { get; set; }
        public virtual DbSet<TBL_Shops5TopProducts> TBL_Shops5TopProducts { get; set; }
        public virtual DbSet<TBL_ShopsInPostalCodes> TBL_ShopsInPostalCodes { get; set; }
        public virtual DbSet<TBL_ShopTypes_CNFG> TBL_ShopTypes_CNFG { get; set; }
        public virtual DbSet<TBL_States_CNFG> TBL_States_CNFG { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<TBL_ControlModule> TBL_ControlModule { get; set; }
        public virtual DbSet<TBL_ControlModule_Pages> TBL_ControlModule_Pages { get; set; }
        public virtual DbSet<TBL_Menues> TBL_Menues { get; set; }
        public virtual DbSet<TBL_Page_Menues> TBL_Page_Menues { get; set; }
        public virtual DbSet<TBL_Page_Plugins> TBL_Page_Plugins { get; set; }
        public virtual DbSet<TBL_Pages> TBL_Pages { get; set; }
        public virtual DbSet<TBL_PlugIn_Details> TBL_PlugIn_Details { get; set; }
        public virtual DbSet<TBL_PlugInCities> TBL_PlugInCities { get; set; }
        public virtual DbSet<TBL_PlugInImages> TBL_PlugInImages { get; set; }
        public virtual DbSet<TBL_PlugIns> TBL_PlugIns { get; set; }
        public virtual DbSet<TBL_Shop_PlugIn> TBL_Shop_PlugIn { get; set; }
        public virtual DbSet<TBL_UserAssignedShops> TBL_UserAssignedShops { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ShopMapDetails> TBL_ShopMapDetails { get; set; }
    }
}
