//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.DB.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PlugIns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PlugIns()
        {
            this.TBL_Page_Plugins = new HashSet<TBL_Page_Plugins>();
            this.TBL_PlugInCities = new HashSet<TBL_PlugInCities>();
            this.TBL_PlugInImages = new HashSet<TBL_PlugInImages>();
            this.TBL_Shop_PlugIn = new HashSet<TBL_Shop_PlugIn>();
        }
    
        public int PlugInID { get; set; }
        public string PlugInName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string VideoDescriptionUrl { get; set; }
        public Nullable<bool> IsPlugInPerShop { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<bool> IsFreeToAll { get; set; }
        public Nullable<bool> IsPageType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Page_Plugins> TBL_Page_Plugins { get; set; }
        public virtual TBL_PlugIn_Details TBL_PlugIn_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PlugInCities> TBL_PlugInCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PlugInImages> TBL_PlugInImages { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Shop_PlugIn> TBL_Shop_PlugIn { get; set; }
    }
}
