//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.DB.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PlugIn_Details
    {
        public int PlugInID { get; set; }
        public Nullable<int> NoOfCondition { get; set; }
    
        public virtual TBL_PlugIns TBL_PlugIns { get; set; }
    }
}
