//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.DB.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Shops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Shops()
        {
            this.TBL_InActiveShopList_CNFG = new HashSet<TBL_InActiveShopList_CNFG>();
            this.TBL_Products = new HashSet<TBL_Products>();
            this.TBL_ShopOffers = new HashSet<TBL_ShopOffers>();
            this.TBL_ShopsInPostalCodes = new HashSet<TBL_ShopsInPostalCodes>();
            this.TBL_Shops5TopProducts = new HashSet<TBL_Shops5TopProducts>();
        }
    
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string OwnerName { get; set; }
        public string ContactNumber { get; set; }
        public string WhatsAppHikeNumber { get; set; }
        public int ShopTypeID { get; set; }
        public Nullable<System.TimeSpan> ShopOpningTime { get; set; }
        public Nullable<System.TimeSpan> ShopClosingTime { get; set; }
        public Nullable<int> InfrastructureID { get; set; }
        public string ShopAddress { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public int ShopCategoryID { get; set; }
        public Nullable<int> ShopDirectoryID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_InActiveShopList_CNFG> TBL_InActiveShopList_CNFG { get; set; }
        public virtual TBL_InfrastructureCategories_CNFG TBL_InfrastructureCategories_CNFG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Products> TBL_Products { get; set; }
        public virtual TBL_ShopCategory_CNFG TBL_ShopCategory_CNFG { get; set; }
        public virtual TBL_ShopDirectory TBL_ShopDirectory { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ShopOffers> TBL_ShopOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ShopsInPostalCodes> TBL_ShopsInPostalCodes { get; set; }
        public virtual TBL_ShopTypes_CNFG TBL_ShopTypes_CNFG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Shops5TopProducts> TBL_Shops5TopProducts { get; set; }
    }
}
