//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.DB.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ControlModule_Pages
    {
        public int ControlModule_PagesID { get; set; }
        public Nullable<int> ControlModuleId { get; set; }
        public Nullable<int> PageId { get; set; }
    
        public virtual TBL_ControlModule TBL_ControlModule { get; set; }
        public virtual TBL_Pages TBL_Pages { get; set; }
    }
}
