//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BS.DB.EntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ShopOffers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ShopOffers()
        {
            this.TBL_OfferOnProducts = new HashSet<TBL_OfferOnProducts>();
        }
    
        public int OfferID { get; set; }
        public int ShopID { get; set; }
        public string OfferShortText { get; set; }
        public Nullable<System.DateTime> OfferStartDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public string OfferOnBrand { get; set; }
        public bool IsOfferOnProducts { get; set; }
        public bool IsActive { get; set; }
        public string OfferDetailText { get; set; }
        public byte[] OfferImage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_OfferOnProducts> TBL_OfferOnProducts { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails { get; set; }
        public virtual TBL_ShopLoginDetails TBL_ShopLoginDetails1 { get; set; }
        public virtual TBL_Shops TBL_Shops { get; set; }
    }
}
